env:
  TERM: alacritty

window:
  padding:
    x: 8
    y: 8

  dynamic_padding: true 

  decorations: none
  startup_mode: Windowed
  title: Alacritty

# Font configuration
font:
  normal:
    family: Inconsolata 
    style: Regular

  bold:
    family: Inconsolata
    style: Regular

  italic:
    family: Inconsolata
    style: Italic

  bold_italic:
    family: Inconsolata
    style: Italic

  size: 11.0

bell:
  duration: 0
  command: None

cursor:
  style: Block
