env:
  TERM: alacritty

  # WINDOW
window:
  padding:
    x: 8
    y: 8

  dynamic_padding: true 

  decorations: none
  startup_mode: Windowed
  title: Alacritty

# Font configuration
font:
  # normal:
  #   family: Misc Tamsyn
  #   style: Regular 

  # bold:
  #   family: Misc Tamsyn
  #   style: Regular 

  # size: 11

  normal:
    family: Jetbrains Mono
    style: Regular 

  bold:
    family: Jetbrains Mono 
    style: Regular 

  size: 10

bell:
  duration: 0
  command: None

cursor:
  style: Block
