[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias la='ls -la --color=auto'

source /usr/share/fzf/completion.bash
source /usr/share/fzf/key-bindings.bash

right_prompt() 
{
	git_output=$(git branch --show-current 2> /dev/null)
	if [ $? -eq "0" ]; then
        echo ":$git_output"
	fi
}

PS1='\W$(right_prompt) > '
