#! /bin/sh

sxhkd &

# Because Java 
# See https://wiki.archlinux.org/index.php/Bspwm#Problems_with_Java_applications
wmname LG3D 

if xrand | grep "HDMI1 connected" &> /dev/null ; then
	bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         0
bspc config window_gap           24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
